### PR TITLE
New CleverBot API update fix

### PR DESCRIPTION
**Pull request by Lukhajek**
It was returning undefined so I fixed it.

### CODE REVIEW

**Comment by SathvikHegde** [comment]
Thanks

**Comment by Arda1984** [comment]
Hm, I still have that problem

**Comment by Lukhajek** [comment]
> Hm, I still have that problem

It's not merged yet. You have to download it from [here](https://github.com/Lukhajek/cleverbot-free) if you haven't done so.

**Comment by Arda1984** [comment]
> > Hm, I still have that problem
> 
> It's not merged yet. You have to download it from [here](https://github.com/Lukhajek/cleverbot-free) if you haven't done so.

Ah now it works, thanks :)

**Pull request merged**
