### PR TITLE
use yarn and add typings

### PR DESCRIPTION
**Pull request by Milo123459**
Hello! This is a pull request that add's typings and uses yarn.lock instead of package-lock.json
This is mainly focused on typings, but yarn can be seen as a "helpful" addition.

### CODE REVIEW

**Comment by Milo123459** [comment]
@IntriguingTiles bump

**Comment by ViniDalvino** [comment]
bump. I want this this be added  @IntriguingTiles

**Comment by Milo123459** [comment]
at least someone cares hahah

**Comment by ViniDalvino** [comment]
@Milo123459 for now what i do is setting the flag `allowJs` to true and loading the module from a js file. it's far from perfect but it does the job. here is how i do it: 
./cleverbot-handler.js:
```js
const cleverbot = require("cleverbot-free")

const CleverBotConvoHistory = [];
const SHOULD_USE_CONVO_HISTORY = true;

async function chat_clever(msg) {
  
  const answer = await cleverbot(msg, CleverBotConvoHistory);

  if (SHOULD_USE_CONVO_HISTORY)
  {
    CleverBotConvoHistory.push(msg);
    CleverBotConvoHistory.push(answer);
  }

  return answer;
}

export default chat_clever;
```
index.ts:
```ts
import { chat_clever } from "./cleverbot.js";
chat_clever("Hello!").then(console.log)

**Pull request merged**
